branches: 
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github":
    assets:
      - { path: "tmp/cli", label: "Debian Exe"}
